openapi: "3.0.0"
info:
  title: User Management Contract
  version: 2.0.0

paths:
  /register:
    post:
      operationId: register
      tags:
        - user
      description: Register to have access to our system
      requestBody:
        description: Input user information that will be submitted
        content:
          application/json:
            schema:
              properties:
                firstName:
                  type: string
                  example: John
                lastName:
                  type: string
                  example: Doe
                dob:
                  type: string
                  format: date-time
                  example: '2000-07-09T19:44:13.720Z'
                phone:
                  type: string
                  example: '07032543523'
                email:
                  type: string
                  example: "joh.doe@test.com"

      responses:
        "200":
          description: Registration was successful
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: number
                  firstName:
                    type: string
                  lastName:
                    type: string
                  dob:
                    type: string
                    format: date-time
                  phone:
                    type: string
                  email:
                    type: string
