openapi: 3.0.3
info:
  title: Tenant Registration API
  version: 1.1.0
  description: API for registering tenants, validating input, verifying token, and sending notifications in a multi-tenant system.

servers:
  - url: '{protocol}://{environment}/api'
    description: Production server
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      environment:
        default: tenant.zimesfield.com    # Local server
        enum:
          - localhost:8082
          - tenant.zimesfield.com
  - url: '{protocol}://{environment}/api'
    description: Production server
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      environment:
        default: l.zimesfield.com    # Local server
        enum:
          - localhost:9080
          - keycloak.zimesfield.com
security:
  - oauth: [ tenant, email, profile ]
  - openId: [ tenant, email, profile ]

paths:
  /tenants/register:
    $ref: './paths/tenant/register.yaml'

  /tenants/{uuid}:
    $ref: './paths/tenant/tenant.yaml'

  /tenants/{uuid}/email:
    $ref: './paths/tenant/update-email.yaml'

  /tenants/verify/{token}:
    $ref: './paths/tenant/verify-token.yaml'

components:
  securitySchemes:
    oauth:
      $ref: './paths/security.yaml#/zimesfield/oauth'