openapi: 3.0.3
info:
  title: Tenant Registration API
  version: 1.1.0
  description: API for registering tenants, validating input, verifying token, and sending notifications in a multi-tenant system.

servers:
  - url: '{protocol}://{environment}/api'
    description: Production server
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      environment:
        default: localhost:8082    # Local server
        enum:
          - localhost:8082
          - tenant.zimesfield.com
tags:
  - name: Register
    description: Register management
  - name: User
    description: Registration for user
  - name: Authenticate
    description: Authenticate user
  - name: Account
    description: User account
  - name: Admin
    description: Operations about user

security:
  - oauth: [ admins,super_admins,finance,secretaries,users ]

paths:
  /tenants/register:
    $ref: './paths/tenant/register.yaml'

  /tenants/{uuid}:
    $ref: './paths/tenant/tenant.yaml'

  /tenants/{uuid}/email:
    $ref: './paths/tenant/update-email.yaml'

  /tenants/verify/{token}:
    $ref: './paths/tenant/verify-token.yaml'

  /admin/users/{login}:
    $ref: './paths/user/managed-user.yaml'


  /activate:
    $ref: './paths/user/activate.yaml'

  /api/authenticate:
    $ref: './paths/user/login.yaml'

  /authenticated:
    $ref: './paths/user/authenticate.yaml'

  /account:
    $ref: './paths/user/account.yaml'

  /register:
    $ref: './paths/user/register.yaml'

  /account/change-password:
    $ref: './paths/user/change-password.yaml'

  /account/reset-password/init:
    $ref: './paths/user/reset-password-init.yaml'

  /account/reset-password/finish:
    $ref: './paths/user/reset-password-finished.yaml'

components:
  securitySchemes:
    oauth:
      $ref: './paths/security.yaml#/zimesfield/oauth'