openapi: 3.0.1
info:
  title: YCP OLMPH User API Contract
  description: 'This is the user contract for registration.  You can find out more about OLMPH
    at [https://ycpolmphajah.com](https://ycpolmphajah.com).'
  termsOfService: 'https://swagger.io/terms/'
  contact:
    email: comenuko@zimesfield.com
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0
servers:
  - url: '{protocol}://{environment}/services/user'
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      environment:
        default: localhost:8081    # Local server
        enum:
          - localhost:8081
          - api         # Production server
          - api.dev     # Development server
          - api.staging # Staging server

tags:
  - name: Register
    description: Registration for user
  - name: Authenticate
    description: Authenticate user
  - name: Account
    description: User account
  - name: Admin
    description: Operations about user

security:
  - oauth: [ user, email, profile ]
  - openId: [ user, email, profile ]

paths:
  /api/login:
    $ref: './paths/user/login.yaml'
  /api/admin/users/{login}:
    $ref: './paths/user/managed-user.yaml'

  /api/activate:
    $ref: './paths/user/activate.yaml'

  /api/authenticated:
    $ref: './paths/user/authenticate.yaml'

  /api/account:
    $ref: './paths/user/account.yaml'

  /api/register:
    $ref: './paths/user/register.yaml'

  /api/account/change-password:
    $ref: './paths/user/change-password.yaml'

  /api/account/reset-password/init:
    $ref: './paths/user/reset-password-init.yaml'

  /api/account/reset-password/finish:
    $ref: './paths/user/reset-password-finished.yaml'

components:
  securitySchemes:
    oauth:
      type: oauth2
      description: OAuth2 with Keycloak
      flows:
        authorizationCode:
          authorizationUrl: http://localhost:9080/realms/zimesfield/protocol/openid-connect/auth
          tokenUrl: http://localhost:9080/realms/zimesfield/protocol/openid-connect/token
          scopes:
            openid: Zimesfeld specific claims
            email: Email claims
            profile: Profile claims
    openId:
      type: openIdConnect
      openIdConnectUrl: http://localhost:9080/realms/jhipster/.well-known/openid-configuration
